name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs when committing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve

    - name: SSH into EC2 & Restart Docker Container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull flask-app:latest
          sudo docker stop flask-container || true
          sudo docker rm flask-container || true
          sudo docker run -d --name flask-container -p 5000:5000 flask-app
